apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: envoy
  namespace: envoy-gateway-system
spec:
  logLevel: info
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 1

